"""Initial migration

Revision ID: 20945589f03e
Revises: 364e9f861cd6
Create Date: 2025-03-02 17:14:04.938779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20945589f03e'
down_revision = '364e9f861cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domanda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etichetta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('feedback_basso', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_medio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_alto', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domanda', schema=None) as batch_op:
        batch_op.drop_column('feedback_alto')
        batch_op.drop_column('feedback_medio')
        batch_op.drop_column('feedback_basso')
        batch_op.drop_column('etichetta')

    # ### end Alembic commands ###
