"""Initial migration

Revision ID: 364e9f861cd6
Revises: 
Create Date: 2025-03-02 16:56:31.218558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364e9f861cd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_risposte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('min_valore', sa.Float(), nullable=False),
    sa.Column('max_valore', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testo', sa.Text(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('attiva', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('risposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('risposte', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('media_motivazione', sa.Float(), nullable=True),
    sa.Column('media_risorse', sa.Float(), nullable=True),
    sa.Column('media_elaborazione', sa.Float(), nullable=True),
    sa.Column('media_tempo', sa.Float(), nullable=True),
    sa.Column('media_strategie', sa.Float(), nullable=True),
    sa.Column('media_concentrazione', sa.Float(), nullable=True),
    sa.Column('media_selezione', sa.Float(), nullable=True),
    sa.Column('media_atteggiamento', sa.Float(), nullable=True),
    sa.Column('media_monitoraggio', sa.Float(), nullable=True),
    sa.Column('media_ansia', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_risposta_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risposta')
    op.drop_table('user')
    op.drop_table('domanda')
    op.drop_table('cluster_risposte')
    # ### end Alembic commands ###
